# Generated by Django 2.1.4 on 2019-08-09 15:28

from django.db import migrations, models
import gallary.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(max_length=1000, verbose_name='Description')),
                ('img', models.ImageField(upload_to=gallary.models.get_image_path, verbose_name='')),
                ('category', models.CharField(choices=[('draft', 'draft'), ('published', 'published')], default=('draft', 'draft'), max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
